
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;
	private global::Gtk.Image logoImage;
	private global::Gtk.HBox hbox2;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Entry accountNumEnt;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Entry passEnt;
	private global::Gtk.HBox hbox5;
	private global::Gtk.CheckButton rememberMeCheck;
	private global::Gtk.Button loginButton;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.logoImage = new global::Gtk.Image ();
		this.logoImage.Name = "logoImage";
		this.vbox2.Add (this.logoImage);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.logoImage]));
		w1.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.accountNumEnt = new global::Gtk.Entry ();
		this.accountNumEnt.CanFocus = true;
		this.accountNumEnt.Name = "accountNumEnt";
		this.accountNumEnt.Text = global::Mono.Unix.Catalog.GetString ("Enter 7 Digit Account Number");
		this.accountNumEnt.IsEditable = true;
		this.accountNumEnt.InvisibleChar = '●';
		this.vbox3.Add (this.accountNumEnt);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.accountNumEnt]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		this.vbox3.Add (this.vbox4);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox4]));
		w3.Position = 1;
		// Container child vbox3.Gtk.Box+BoxChild
		this.passEnt = new global::Gtk.Entry ();
		this.passEnt.CanFocus = true;
		this.passEnt.Name = "passEnt";
		this.passEnt.Text = global::Mono.Unix.Catalog.GetString ("Password");
		this.passEnt.IsEditable = true;
		this.passEnt.InvisibleChar = '●';
		this.vbox3.Add (this.passEnt);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.passEnt]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.rememberMeCheck = new global::Gtk.CheckButton ();
		this.rememberMeCheck.CanFocus = true;
		this.rememberMeCheck.Name = "rememberMeCheck";
		this.rememberMeCheck.Label = global::Mono.Unix.Catalog.GetString ("Remember Me");
		this.rememberMeCheck.DrawIndicator = true;
		this.rememberMeCheck.UseUnderline = true;
		this.hbox5.Add (this.rememberMeCheck);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.rememberMeCheck]));
		w5.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.loginButton = new global::Gtk.Button ();
		this.loginButton.CanFocus = true;
		this.loginButton.Name = "loginButton";
		this.loginButton.UseUnderline = true;
		this.loginButton.Label = global::Mono.Unix.Catalog.GetString ("Login");
		this.hbox5.Add (this.loginButton);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.loginButton]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox3.Add (this.hbox5);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		this.hbox2.Add (this.vbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox3]));
		w8.Position = 1;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w9.Position = 1;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.loginButton.Clicked += new global::System.EventHandler (this.OnLoginButtonClicked);
	}
}
